# Generated by Django 2.1.3 on 2018-11-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Description of this course.', verbose_name='Course Description')),
                ('difficulty', models.CharField(blank=True, choices=[('a', 'Advanced'), ('i', 'Intermediate'), ('b', 'Beginner'), ('o', 'Other')], default='o', help_text='The level of difficulty of the course.', max_length=1)),
                ('track', models.CharField(blank=True, choices=[('py', 'Python'), ('pe', 'Perl'), ('ja', 'Java'), ('cpp', 'C++'), ('js', 'Javascript'), ('sc', 'Scala'), ('php', 'PHP'), ('csh', 'C#'), ('go', 'Go'), ('ht', 'HTML'), ('hsk', 'Haskell')], help_text='The programming language the course is being taught in.', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique topic the describes a course.', max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(help_text='Select all relevant topics to this course.', to='courses.Topic'),
        ),
    ]
