# Generated by Django 2.1.3 on 2018-11-16 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181115_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('py', 'Python'), ('pe', 'Perl'), ('ja', 'Java'), ('cpp', 'C++'), ('js', 'Javascript'), ('sc', 'Scala'), ('php', 'PHP'), ('csh', 'C#'), ('go', 'Go'), ('ht', 'HTML'), ('hsk', 'Haskell')], help_text='The programming language the course is being taught in.', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='track',
            field=models.ForeignKey(help_text='The language this course is being taught in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Track'),
        ),
    ]
