# Generated by Django 2.1.3 on 2018-11-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181116_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='language',
            field=models.CharField(help_text='The programming language the course is being taught in.', max_length=25),
        ),
    ]
